//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_WS_Host.Lib {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Lib.ILib")]
    public interface ILib {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILib/GetTacGia", ReplyAction="http://tempuri.org/ILib/GetTacGiaResponse")]
        string GetTacGia(string TacPham);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibChannel : Use_WS_Host.Lib.ILib, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibClient : System.ServiceModel.ClientBase<Use_WS_Host.Lib.ILib>, Use_WS_Host.Lib.ILib {
        
        public LibClient() {
        }
        
        public LibClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTacGia(string TacPham) {
            return base.Channel.GetTacGia(TacPham);
        }
    }
}
